name: gw_sms
description: Gateway SMS
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  get_ip_address: ^0.0.7
  go_router: ^17.0.1
  http: ^1.6.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.2
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.10.5
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  json_serializable: ^6.11.4
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    # common assets
    - assets/common/logos/

    # cliente1
    - assets/cliente1/logos/

    # cliente2
    - assets/cliente2/logos/
